# Generated by Django 3.2.9 on 2023-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=160, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=160, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профиль',
            },
        ),
    ]
