# Generated by Django 3.2.9 on 2023-09-20 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_operation_stanprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Марка, модель станка')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станок',
            },
        ),
        migrations.AlterField(
            model_name='stanprofile',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.operation', verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='stanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='stanprofile',
            name='machines',
            field=models.ManyToManyField(to='profiles.Machine'),
        ),
    ]
