# Generated by Django 3.2.9 on 2021-11-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211123_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='не определено', max_length=160, null=True, verbose_name='наименование')),
                ('machine', models.CharField(blank=True, max_length=160, null=True, verbose_name='оборудование')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workplace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.workplace', verbose_name='рабочее место'),
        ),
    ]
