# Generated by Django 3.2.9 on 2021-11-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
        ('profiles', '0003_auto_20211123_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='workplace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='рабочее место'),
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
    ]
