# Generated by Django 3.2.9 on 2021-11-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0002_alter_workplace_options'),
        ('profiles', '0004_auto_20211123_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='рабочее место'),
        ),
    ]
