# Generated by Django 3.2.9 on 2023-08-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211123_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workplace',
        ),
    ]
