# Generated by Django 3.2.9 on 2024-07-15 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0025_alter_toolsonwarehouse_title'),
        ('profiles', '0003_auto_20230920_1107'),
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolsonwarehousezn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='Кол-во')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Деталь')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Детали',
                'verbose_name_plural': 'Детали на складе',
            },
        ),
        migrations.CreateModel(
            name='Toolszn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='Кол-во')),
                ('giveout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('and_priem', models.BooleanField(default=False, verbose_name='С приемом на склад')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zink.toolsonwarehousezn', verbose_name='Деталь')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдача деталей',
            },
        ),
        migrations.CreateModel(
            name='Priemzn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True, verbose_name='Кол-во')),
                ('giveout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zink.toolsonwarehousezn', verbose_name='Детали')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник, от которого принята деталь')),
            ],
            options={
                'verbose_name': 'прием',
                'verbose_name_plural': 'прием деталей на склад',
            },
        ),
    ]
