# Generated by Django 3.2.9 on 2024-07-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_alter_toolsonwarehouse_title'),
        ('zink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priemzn',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Детали'),
        ),
    ]
