# Generated by Django 3.2.9 on 2024-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zink', '0002_alter_priemzn_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehousezn',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
