# Generated by Django 3.2.9 on 2023-09-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0004_alter_toolsonwarehouse_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата выполнения работы')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Детали')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Выполненные работы',
                'verbose_name_plural': 'Выполненные работы',
            },
        ),
    ]
