# Generated by Django 3.2.9 on 2023-09-20 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
