# Generated by Django 3.2.9 on 2023-10-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='machines',
        ),
    ]
