# Generated by Django 3.2.9 on 2023-11-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230920_1107'),
        ('work', '0009_remove_work_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='machines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.machine', verbose_name='Станки'),
        ),
    ]
