# Generated by Django 3.2.9 on 2024-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20231107_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='ready',
            field=models.BooleanField(default=True, verbose_name='Опер. завершена?'),
        ),
    ]
