# Generated by Django 3.2.9 on 2024-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_work_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время выполнения одной детали на данной операции, мин'),
        ),
    ]
