# Generated by Django 3.2.9 on 2024-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_alter_work_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='numb_ust',
            field=models.IntegerField(default=1, verbose_name='Номер установа'),
        ),
    ]
