# Generated by Django 3.2.9 on 2024-05-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_work_numb_ust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='numb_ust',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='Номер установа'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время на одну дет., мин'),
        ),
    ]
