# Generated by Django 3.2.9 on 2024-07-24 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20230920_1107'),
        ('tools', '0025_alter_toolsonwarehouse_title'),
        ('work', '0016_auto_20240507_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workoptim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата предложения')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('machines', models.ManyToManyField(blank=True, null=True, to='profiles.Machine', verbose_name='Станки')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Детали')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Рационализаторские предложения',
                'verbose_name_plural': 'Рационализаторские предложения',
            },
        ),
    ]
