# Generated by Django 3.2.9 on 2021-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True, verbose_name='наименование')),
                ('machine', models.CharField(blank=True, max_length=160, null=True, verbose_name='оборудование')),
            ],
        ),
    ]
