# Generated by Django 3.2.9 on 2021-11-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'рабочее место', 'verbose_name_plural': 'пабочее место'},
        ),
    ]
