# Generated by Django 3.2.9 on 2021-11-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0002_alter_workplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'рабочее место', 'verbose_name_plural': 'рабочее место'},
        ),
    ]
