# Generated by Django 3.2.9 on 2023-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0003_alter_workplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Место хранения', 'verbose_name_plural': 'Место хранения'},
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='machine',
        ),
        migrations.AddField(
            model_name='workplace',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Наименование'),
        ),
    ]
