# Generated by Django 3.2.9 on 2021-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='count',
            field=models.IntegerField(),
        ),
    ]
