# Generated by Django 3.2.9 on 2023-08-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения'),
        ),
    ]
