# Generated by Django 3.2.9 on 2021-11-19 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tools_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsonwarehouse',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструмент'},
        ),
        migrations.AlterField(
            model_name='tools',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения на склад'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Обозначение'),
        ),
    ]
