# Generated by Django 3.2.9 on 2021-11-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20211119_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsonwarehouse',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструмент на складе'},
        ),
        migrations.AddField(
            model_name='tools',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse'),
        ),
    ]
