# Generated by Django 3.2.9 on 2021-11-22 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0004_auto_20211122_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='title',
        ),
        migrations.AlterField(
            model_name='tools',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='giveout_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='reason_of_return',
            field=models.TextField(verbose_name='Причина возврата'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Инструмент'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
