# Generated by Django 3.2.9 on 2023-09-20 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolsonwarehouse_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
