# Generated by Django 3.2.9 on 2021-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20211122_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдача инструмента'},
        ),
        migrations.AlterField(
            model_name='tools',
            name='reason_of_return',
            field=models.TextField(blank=True, null=True, verbose_name='Причина возврата'),
        ),
    ]
