# Generated by Django 3.2.9 on 2023-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_toolsonwarehouse_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='cover',
            field=models.BooleanField(default=True, verbose_name='Деталь покрывается?'),
        ),
    ]
