# Generated by Django 3.2.9 on 2021-11-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211123_0945'),
        ('tools', '0006_auto_20211122_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник'),
        ),
    ]
