# Generated by Django 3.2.9 on 2023-09-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_remove_toolsonwarehouse_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='Покрывается'),
        ),
    ]
