# Generated by Django 3.2.9 on 2021-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_tools_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='period',
            field=models.CharField(choices=[('LGP', 'Долгий срок'), ('SHP', 'Расходник')], default='SHP', max_length=3),
        ),
    ]
