# Generated by Django 3.2.9 on 2021-11-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_toolsonwarehouse_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='min_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='period',
            field=models.CharField(choices=[('LGP', 'Долгий срок'), ('SHP', 'Расходник')], default='SHP', max_length=3, verbose_name='Срок эксплуотации'),
        ),
    ]
