# Generated by Django 3.2.9 on 2023-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230920_1107'),
        ('workplace', '0001_initial'),
        ('tools', '0008_toolsonwarehouse_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='and_priem',
            field=models.BooleanField(default=False, verbose_name='С приемом на склад'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник, от которого принята деталь'),
        ),
    ]
