# Generated by Django 3.2.9 on 2021-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20211129_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='min_count',
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='min_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество'),
        ),
    ]
