# Generated by Django 3.2.9 on 2023-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20231024_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_electro',
            field=models.FloatField(blank=True, default=0, verbose_name='Электроэрозионная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_lentopil',
            field=models.FloatField(blank=True, default=0, verbose_name='Ленточнопильная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_mill',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезерная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_plazma',
            field=models.FloatField(blank=True, default=0, verbose_name='Плазма, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_rastoch',
            field=models.FloatField(blank=True, default=0, verbose_name='Расточная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_slesarn',
            field=models.FloatField(blank=True, default=0, verbose_name='Слесарная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_sverliln',
            field=models.FloatField(blank=True, default=0, verbose_name='Сверлильная, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_turn',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарная, ч.'),
        ),
    ]
