# Generated by Django 3.2.9 on 2023-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20231128_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_electro_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Электроэрозионная п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_lentopil_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Ленточнопильная п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_mill_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезернаяп/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_plazma_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Плазма п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_rastoch_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Расточная п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_sverliln_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Сверлильная п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_turn_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарнаяп/з, ч.'),
        ),
    ]
