# Generated by Django 3.2.9 on 2023-11-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20231128_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_millun',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезерная универс. , ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_millun_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезерная универс. п/з, ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_turnun',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарная универс., ч.'),
        ),
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='norm_turnun_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарная универс. п/з, ч.'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='norm_mill',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезерная ЧПУ, ч.'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='norm_mill_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Фрезерная ЧПУ п/з, ч.'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='norm_turn',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарная ЧПУ, ч.'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='norm_turn_p',
            field=models.FloatField(blank=True, default=0, verbose_name='Токарная ЧПУ п/з, ч.'),
        ),
    ]
