# Generated by Django 3.2.9 on 2024-02-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
        ('tools', '0012_auto_20231129_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения'),
        ),
    ]
