# Generated by Django 3.2.9 on 2024-02-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('tools', '0013_alter_toolsonwarehouse_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='material_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material', verbose_name='Материал'),
        ),
    ]
