# Generated by Django 3.2.9 on 2022-01-10 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211123_0945'),
        ('tools', '0013_alter_tools_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='reason_of_return',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='return_date',
        ),
        migrations.CreateModel(
            name='Rec_Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('count', models.IntegerField(null=True, verbose_name='Кол-во')),
                ('giveout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сдачи')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Инструмент')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Сдача',
                'verbose_name_plural': 'Сдача отработанного инструмента',
            },
        ),
    ]
