# Generated by Django 3.2.9 on 2024-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_toolsonwarehouse_material_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsonwarehouse',
            name='similar',
            field=models.ManyToManyField(related_name='_tools_toolsonwarehouse_similar_+', to='tools.Toolsonwarehouse'),
        ),
    ]
