# Generated by Django 3.2.9 on 2022-01-10 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20220110_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True, verbose_name='Кол-во')),
                ('giveout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Инструмент')),
            ],
        ),
    ]
