# Generated by Django 3.2.9 on 2024-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_toolsonwarehouse_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='similar',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tools_toolsonwarehouse_similar_+', to='tools.Toolsonwarehouse', verbose_name='Похожие'),
        ),
    ]
