# Generated by Django 3.2.9 on 2023-08-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0003_alter_workplace_options'),
        ('profiles', '0005_auto_20211123_0945'),
        ('tools', '0015_priem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priem',
            options={'verbose_name': 'прием', 'verbose_name_plural': 'прием деталей на склад'},
        ),
        migrations.AlterModelOptions(
            name='rec_tools',
            options={'verbose_name': 'Брак', 'verbose_name_plural': 'Отбракованные детали'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдача деталей'},
        ),
        migrations.AlterModelOptions(
            name='toolsonwarehouse',
            options={'verbose_name': 'Детали', 'verbose_name_plural': 'Детали на складе'},
        ),
        migrations.RemoveField(
            model_name='toolsonwarehouse',
            name='min_count',
        ),
        migrations.RemoveField(
            model_name='toolsonwarehouse',
            name='need_count',
        ),
        migrations.RemoveField(
            model_name='toolsonwarehouse',
            name='period',
        ),
        migrations.AddField(
            model_name='priem',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='priem',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник, от которого принята деталь'),
        ),
        migrations.AlterField(
            model_name='priem',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='rec_tools',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Деталь'),
        ),
    ]
