# Generated by Django 3.2.9 on 2023-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20230801_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество на складе'),
        ),
    ]
