# Generated by Django 3.2.9 on 2024-05-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_norms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun1',
            new_name='cncturn1',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun2',
            new_name='cncturn2',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun3',
            new_name='cncturn3',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun4',
            new_name='cncturn4',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun5',
            new_name='cncturn5',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun6',
            new_name='cncturn6',
        ),
        migrations.RenameField(
            model_name='norms',
            old_name='cnctun7',
            new_name='cncturn7',
        ),
    ]
