# Generated by Django 3.2.9 on 2024-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20240507_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='cncmill0',
            field=models.IntegerField(null=True, verbose_name='фрез. чпу 0 уст.'),
        ),
        migrations.AddField(
            model_name='norms',
            name='cncturn0',
            field=models.IntegerField(null=True, verbose_name='ток. чпу 0 уст.'),
        ),
    ]
