# Generated by Django 3.2.9 on 2024-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_auto_20240507_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='cncmill0',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 0 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill1',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 1 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill2',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 2 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill3',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 3 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill4',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 4 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill5',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 5 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill6',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 6 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncmill7',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. чпу 7 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn0',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 0 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn1',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 1 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn2',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 2 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn3',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 3 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn4',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 4 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn5',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 5 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn6',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 6 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='cncturn7',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. чпу 7 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz0',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 0 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz1',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 1 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz2',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 2 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz3',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 3 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz4',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 4 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz5',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 5 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz6',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 6 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='eroz7',
            field=models.IntegerField(blank=True, null=True, verbose_name='эроз 7 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='lentopil',
            field=models.IntegerField(blank=True, null=True, verbose_name='пила'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill0',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 0 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill1',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 1 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill2',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 2 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill3',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 3 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill4',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 4 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill5',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 5 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill6',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 6 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='mill7',
            field=models.IntegerField(blank=True, null=True, verbose_name='фрез. ун. 7 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn0',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 0 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn1',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 1 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn2',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 2 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn3',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 3 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn4',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 4 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn5',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 5 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn6',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 6 уст.'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='turn7',
            field=models.IntegerField(blank=True, null=True, verbose_name='ток. ун. 7 уст.'),
        ),
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Обозначение'),
        ),
    ]
