# Generated by Django 3.2.9 on 2024-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_auto_20240529_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Обозначение'),
        ),
    ]
