# Generated by Django 3.2.9 on 2024-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_alter_toolsonwarehouse_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsonwarehouse',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Обозначение'),
        ),
    ]
