# Generated by Django 3.2.9 on 2023-08-02 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Изделие')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Изделия(заказы)',
                'verbose_name_plural': 'Изделия(заказы)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('order_date_worker', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запуска')),
                ('status', models.CharField(choices=[('OW', 'В запуске'), ('OR', 'запущено'), ('PD', 'на стороне'), ('CM', 'изготовлено')], default='OW', editable=False, max_length=2, verbose_name='статус')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.firm', verbose_name='Изделие(заказ)')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Детали по изделиям',
                'verbose_name_plural': 'Детали по изделиям',
            },
        ),
        migrations.CreateModel(
            name='Orderformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.TextField(blank=True, null=True, verbose_name='Номер счета')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('OW', 'В запуске'), ('OR', 'запущено'), ('PD', 'на стороне'), ('CM', 'изготовлено')], default='OW', max_length=2, verbose_name='статус')),
                ('tools', models.ManyToManyField(blank=True, null=True, to='order.Order', verbose_name='Инструменты')),
            ],
            options={
                'verbose_name': 'Сформированные заказы',
                'verbose_name_plural': 'Сформированные заказы',
            },
        ),
    ]
