# Generated by Django 3.2.9 on 2021-11-23 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_auto_20211123_0945'),
        ('tools', '0007_alter_tools_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фирмы')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Поставщики',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('order_date_worker', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('OW', 'Заявка от работника'), ('OR', 'Заказан'), ('PD', 'Оплачен'), ('CM', 'На складе')], default='OW', max_length=2)),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.firm', verbose_name='Поставщик')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.toolsonwarehouse', verbose_name='Инструмент')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Работник, которому заказывается инструмент')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдача инструмента',
            },
        ),
    ]
