# Generated by Django 3.2.9 on 2021-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ инструмента', 'verbose_name_plural': 'Заказ инструмента'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OW', 'Заявка'), ('OR', 'Заказан'), ('PD', 'Оплачен'), ('CM', 'Получено')], default='OW', max_length=2, verbose_name='статус'),
        ),
    ]
