# Generated by Django 3.2.9 on 2023-08-04 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срокизготовления'),
        ),
    ]
