# Generated by Django 3.2.9 on 2023-08-04 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срокизготовления'),
        ),
    ]
