# Generated by Django 3.2.9 on 2021-12-01 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20211201_2058'),
        ('order', '0002_auto_20211126_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OW', 'Заявка'), ('OR', 'Заказан'), ('PD', 'Оплачен'), ('CM', 'Получено')], default='OW', editable=False, max_length=2, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='Orderformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.TextField(blank=True, null=True, verbose_name='Номер счета')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('tools', models.ManyToManyField(to='tools.Toolsonwarehouse')),
            ],
            options={
                'verbose_name': 'Сформированные заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
