# Generated by Django 3.2.9 on 2021-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211201_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderformed',
            options={'verbose_name': 'Сформированные заказы', 'verbose_name_plural': 'Сформированные заказы'},
        ),
        migrations.AddField(
            model_name='orderformed',
            name='status',
            field=models.CharField(choices=[('OW', 'Заявка'), ('OR', 'Заказан'), ('PD', 'Оплачен'), ('CM', 'Получено')], default='OW', editable=False, max_length=2, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderformed',
            name='tools',
            field=models.ManyToManyField(to='order.Order'),
        ),
    ]
