# Generated by Django 3.2.9 on 2023-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_date',
            field=models.DateField(default=None, null=True, verbose_name='Срок изготовления'),
        ),
    ]
