# Generated by Django 3.2.9 on 2023-08-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Срок изготовления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OW', 'В запуске'), ('OR', 'запущено'), ('PD', 'на стороне'), ('CM', 'изготовлено')], default='OW', max_length=2, verbose_name='статус'),
        ),
    ]
