# Generated by Django 3.2.9 on 2023-08-01 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_alter_toolsonwarehouse_count'),
        ('order', '0005_auto_20211215_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Изделия(заказы)', 'verbose_name_plural': 'Изделия(заказы)'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='worker',
        ),
        migrations.AlterField(
            model_name='firm',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.firm', verbose_name='Изделие(заказ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_worker',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запуска'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tool',
        ),
        migrations.AddField(
            model_name='order',
            name='tool',
            field=models.ManyToManyField(to='tools.Toolsonwarehouse'),
        ),
    ]
