# Generated by Django 3.2.9 on 2023-08-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20230829_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderformed',
            name='tools',
        ),
    ]
