# Generated by Django 3.2.9 on 2023-08-29 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderformed_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запуска'),
        ),
        migrations.AddField(
            model_name='firm',
            name='exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Срок изготовления'),
        ),
    ]
