# Generated by Django 3.2.9 on 2023-08-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_order_date_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date_worker',
        ),
    ]
