# Generated by Django 3.2.9 on 2023-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_firm_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cover',
            field=models.BooleanField(default=True, verbose_name='Деталь покрывается?'),
        ),
    ]
