# Generated by Django 3.2.9 on 2023-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='Деталь покрывается?'),
        ),
    ]
