# Generated by Django 3.2.9 on 2023-09-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cover',
        ),
    ]
