# Generated by Django 3.2.9 on 2023-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во'),
        ),
    ]
