# Generated by Django 3.2.9 on 2024-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Готов'),
        ),
    ]
