# Generated by Django 3.2.9 on 2024-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_firm_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='folder',
            field=models.URLField(blank=True, null=True, verbose_name='pdf'),
        ),
    ]
