# Generated by Django 3.2.9 on 2024-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='folder',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Folder'),
        ),
    ]
