# Generated by Django 3.2.9 on 2024-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_toolsonwarehouse_similar'),
        ('order', '0027_auto_20240402_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assem',
            name='tool_count',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='assem_count',
        ),
        migrations.AlterField(
            model_name='assem',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Toolsonwarehouse', verbose_name='Детали'),
        ),
    ]
